model:
  encoder:
    type: hf_encoder
    pretrained_model_name_or_path: hfl/chinese-roberta-wwm-ext
    hidden_dropout_prob: 0.1
  head:
    type: crf
    # num_tags 由代码自动注入，无需手动填写

train:
  batch_size: 16               # GTX1650 4GB 安全值
  # batch_size: 8 
  gradient_accumulation_steps: 4  # 等效 batch=64
  bert_lr: 3.0e-5
  crf_lr: 1.0e-3
  weight_decay: 0.01
  max_grad_norm: 1.0
  fp16: true                   # GTX1650 必须开启
  # num_epochs: 10
  num_epochs: 1
  output_dir: checkpoints/duee_top10

data:
  max_seq_length: 128